name: commerce-project-base
recipe: drupal9
config:
  webroot: web
  php: '8.0'
  via: nginx
  database: mariadb:10.4

services:
  mailhog:
    type: mailhog:v1.0.0
    portforward: false
    hogfrom:
      - appserver

tooling:
  install:
    service: appserver
    description: Install Application
    cmd:
      - /bin/sh -c "if [ -d web/sites/default ]; then chmod -R +w web/sites/default; fi"
      - cd "$LANDO_MOUNT" && composer --no-ansi --no-interaction install --no-progress --prefer-dist --optimize-autoloader
      - cd "$LANDO_WEBROOT" && drush si commerce_base --db-url=mysql://drupal9:drupal9@database:3306/drupal9 --site-name='Commerce Project' --site-mail='admin@example.com' --account-name='system' --account-mail='system@example.com' --account-pass='system' -y
      - cd "$LANDO_WEBROOT" && drush ucrt admin --password="admin" --mail="admin@example.com"
      - cd "$LANDO_WEBROOT" && drush urol "administrator" admin

  update:
    service: appserver
    description: Update Application
    cmd:
      - /bin/sh -c "if [ -d web/sites/default ]; then chmod -R +w web/sites/default; fi"
      - cd "$LANDO_MOUNT" && composer update
      - cd "$LANDO_WEBROOT" && drush updb
      - cd "$LANDO_WEBROOT" && drush entup

  soften:
    service: appserver
    description: Soften the drupal code
    cmd:
      - /bin/sh -c "if [ -d web/sites/default ]; then chmod -R +w web/sites/default; fi"
